### ISSUE TITLE
How did you configure the environment?

### ISSUE THREAD

**Issue by lazyaa** [johannes-dornheim/Reinforce-FE#1]
How did you configure the environment?When I run random agent.py, it say  can't find the file
```
 File "C:\Users\louziyi\Desktop\Reinforce-FE\gym_fem\fem_wrapper.py", line 215, in run_simulation
    out = check_output(run_cmd, cwd=job_directory, timeout=self.timeout, stderr=subprocess.STDOUT)

  File "C:\Users\louziyi\anaconda3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "C:\Users\louziyi\anaconda3\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\louziyi\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 104, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\louziyi\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)

  File "C:\Users\louziyi\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] 系统找不到指定的文件。


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\louziyi\Desktop\Reinforce-FE\gym_fem\examples\agents\random_agent.py", line 50, in <module>
    ob, reward, done, _ = env.step(action)

  File "C:\Users\louziyi\Desktop\Reinforce-FE\gym_fem\fem_env.py", line 409, in step
    o, r, done, info = super().step(action)

  File "C:\Users\louziyi\anaconda3\lib\site-packages\gym\core.py", line 289, in step
    return self.env.step(action)

  File "C:\Users\louziyi\anaconda3\lib\site-packages\gym\wrappers\monitor.py", line 48, in step
    observation, reward, done, info = self.env.step(action)

  File "C:\Users\louziyi\anaconda3\lib\site-packages\gym\wrappers\time_limit.py", line 18, in step
    observation, reward, done, info = self.env.step(action)

  File "C:\Users\louziyi\Desktop\Reinforce-FE\gym_fem\envs\deep_drawing.py", line 85, in step
    return super().step(action)

  File "C:\Users\louziyi\Desktop\Reinforce-FE\gym_fem\fem_env.py", line 171, in step
    base_simulation_id=self._base_simulation_id)

  File "C:\Users\louziyi\Desktop\Reinforce-FE\gym_fem\fem_wrapper.py", line 284, in run_simulation
    time.sleep(10)

KeyboardInterrupt
```

**Comment by johannes-dornheim** [comment]
whats your abaqus version?
can you run the "run_cmd" manually by putting it into your console?
